# Generated by Django 4.2 on 2025-10-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="image_nas",
            fields=[
                ("image_nas_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("experiment_key", models.CharField(max_length=100)),
                ("dataset", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("search_algorithm", models.CharField(max_length=100)),
                ("layer_candidate", models.CharField(max_length=100)),
                ("max_epochs", models.IntegerField()),
                ("batch_size", models.IntegerField()),
                ("learning_rate", models.FloatField()),
                ("momentum", models.FloatField()),
                ("weight_decay", models.FloatField()),
                ("auxiliary_loss_weight", models.FloatField()),
                ("width", models.IntegerField()),
                ("num_cells", models.IntegerField()),
                ("drop_path_prob", models.IntegerField()),
                ("use_yn", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="multimodal_nas",
            fields=[
                (
                    "multimodal_nas_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("user_id", models.IntegerField()),
                ("experiment_key", models.CharField(max_length=100)),
                ("dataset", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("performance", models.CharField(max_length=100)),
                ("max_epochs", models.IntegerField()),
                ("batch_size", models.IntegerField()),
                ("learning_rate", models.FloatField()),
                ("optimizer", models.CharField(max_length=100)),
                ("lr_scheduler", models.CharField(max_length=100)),
                ("weight_decay", models.FloatField()),
                ("warmup_epochs", models.FloatField()),
                ("label_smoothing", models.FloatField()),
                ("drop_path", models.FloatField()),
                ("use_yn", models.CharField(max_length=1)),
            ],
        ),
    ]
