# Generated by Django 4.2 on 2025-10-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sejong", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="image_nas",
            new_name="ImageNas",
        ),
        migrations.RenameModel(
            old_name="multimodal_nas",
            new_name="MultimodalNas",
        ),
    ]
