# Generated by Django 4.2 on 2025-11-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageNas",
            fields=[
                ("image_nas_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("exp_key", models.CharField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("search_algorithm", models.CharField(max_length=100)),
                ("dataset_name", models.CharField(max_length=100)),
                ("layer_candidates", models.CharField()),
                ("max_epochs", models.IntegerField()),
                ("strategy", models.CharField(max_length=100)),
                ("batch_size", models.IntegerField()),
                ("learning_rate", models.FloatField()),
                ("momentum", models.FloatField()),
                ("weight_decay", models.FloatField()),
                ("gradient_clip_val", models.FloatField()),
                ("width", models.IntegerField()),
                ("num_of_cells", models.IntegerField()),
                ("aux_loss_weight", models.FloatField()),
                ("drop_path_prob", models.IntegerField()),
                ("use_yn", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedZip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("image", "Image NAS"), ("multi", "Multi-modal NAS")],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
