# Generated by Django 4.2 on 2025-11-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultimodalEvo",
            fields=[
                ("evo_id", models.AutoField(primary_key=True, serialize=False)),
                ("exp_key", models.CharField()),
                ("multimodal_nas_id", models.CharField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField()),
                ("max_epochs", models.IntegerField()),
                ("batch_size", models.IntegerField()),
                ("min_param_limits", models.IntegerField()),
                ("param_limits", models.IntegerField()),
                ("select_num", models.IntegerField()),
                ("crossover_num", models.IntegerField()),
                ("mutation_num", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MultimodalNas",
            fields=[
                (
                    "multimodal_nas_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("user_id", models.IntegerField()),
                ("exp_key", models.CharField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField()),
                ("max_epochs", models.IntegerField()),
                ("batch_size", models.IntegerField()),
                ("learning_rate", models.FloatField()),
                ("min_learning_rate", models.FloatField()),
                ("warmup_epochs", models.IntegerField()),
                ("weight_decay", models.FloatField()),
                ("optimizer", models.CharField(max_length=100)),
                ("lr_scheduler", models.CharField(max_length=100)),
                ("use_yn", models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name="imagenas",
            name="layer_candidates",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="imagenas",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
