# Generated by Django 4.2 on 2025-11-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automl", "0002_multimodalevo_multimodalnas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagenas",
            name="search_algorithm",
        ),
        migrations.AlterField(
            model_name="imagenas",
            name="drop_path_prob",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="imagenas",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="imagenas",
            name="use_yn",
            field=models.CharField(default="y", max_length=1),
        ),
        migrations.AlterField(
            model_name="imagenas",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
