# Generated by Django 4.2 on 2025-11-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automl", "0003_remove_imagenas_search_algorithm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagenas",
            name="performance",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="multimodalevo",
            name="multi_exp_key",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="multimodalevo",
            name="performance",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="multimodalevo",
            name="use_yn",
            field=models.CharField(default="", max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="multimodalnas",
            name="performance",
            field=models.FloatField(null=True),
        ),
    ]
