# Generated by Django 4.2 on 2025-11-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automl", "0004_imagenas_performance_multimodalevo_multi_exp_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multimodalevo",
            name="multi_exp_key",
        ),
        migrations.AddField(
            model_name="multimodalevo",
            name="nas_exp_key",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="multimodalevo",
            name="population_num",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
