# Generated by Django 4.2 on 2025-11-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automl", "0006_multimodalevo_dataset_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageRetrain",
            fields=[
                (
                    "image_retrain_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("user_id", models.IntegerField()),
                ("exp_key", models.CharField()),
                ("image_nas_id", models.IntegerField()),
                ("nas_exp_key", models.IntegerField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField()),
                ("dataset_name", models.CharField()),
                ("epoch_num", models.IntegerField()),
            ],
        ),
    ]
